language: cpp
compiler:
  - gcc
  - clang
before_install:
  - echo $LANG
  - echo $LC_ALL
script: make
branches:
  only:
    - master
notifications:
  recipients:
    - dhiana.deva@gmail.com
  email:
    on_success: change
    on_failure: always
env:
  - LANG="en_US.UTF-8"
os:
  - linux
